version: "3.7"
services:
  sql-service-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "jfrsn_123"
      ACCEPT_EULA: "Y"